theme: jekyll-theme-minimal
title: "Academic Profile of Uzoamaka Nwachukwu"

logo: /Assets/Uzoamaka.jpg




author: "Uzoamaka Nwachukwu"

description: "PhD Student, History Department, 

Indiana University"
